export type VocabDifficulty = "easy" | "medium" | "hard";

export interface VocabWord {
  word: string;
  pos: string;
  definition: string;
}

// [word, part of speech, definition]. Kept as tuples rather than object
// literals so a large tiered list stays easy to scan and extend — appending
// a tier is a one-line array push, no other file needs to change.
type Row = readonly [string, string, string];

function toWords(rows: readonly Row[]): VocabWord[] {
  return rows.map(([word, pos, definition]) => ({ word, pos, definition }));
}

const EASY_ROWS: Row[] = [
  ["abandon", "v.", "to leave someone or something behind completely"],
  ["absorb", "v.", "to take in or soak up"],
  ["accurate", "adj.", "free from errors; exactly correct"],
  ["achieve", "v.", "to successfully reach a goal through effort"],
  ["admire", "v.", "to regard with respect or warm approval"],
  ["adventure", "n.", "an exciting or unusual experience"],
  ["advice", "n.", "a suggestion about what someone should do"],
  ["afford", "v.", "to have enough money or resources for something"],
  ["agree", "v.", "to have the same opinion as someone else"],
  ["ancient", "adj.", "belonging to the very distant past"],
  ["announce", "v.", "to make a public or formal statement"],
  ["annual", "adj.", "happening once every year"],
  ["anxious", "adj.", "feeling worried or nervous"],
  ["apparent", "adj.", "clearly visible or understood; obvious"],
  ["appreciate", "v.", "to recognize the value or worth of something"],
  ["approach", "v.", "to come near to something in distance or time"],
  ["appropriate", "adj.", "suitable or proper for the occasion"],
  ["arrange", "v.", "to put things in a particular order"],
  ["arrive", "v.", "to reach a destination"],
  ["assist", "v.", "to help someone do something"],
  ["assume", "v.", "to accept something as true without proof"],
  ["attempt", "v.", "to make an effort to do something"],
  ["attitude", "n.", "a settled way of thinking about someone or something"],
  ["attract", "v.", "to draw attention or interest toward oneself"],
  ["available", "adj.", "able to be used or obtained"],
  ["average", "adj.", "typical or usual; not exceptional"],
  ["avoid", "v.", "to keep away from something"],
  ["aware", "adj.", "having knowledge of a situation"],
  ["awkward", "adj.", "causing embarrassment or difficulty"],
  ["balance", "n.", "an even distribution of weight or amount"],
  ["basic", "adj.", "forming the essential starting point"],
  ["behave", "v.", "to act in a particular way"],
  ["belief", "n.", "something accepted as true"],
  ["benefit", "n.", "an advantage gained from something"],
  ["bitter", "adj.", "having a sharp, unpleasant taste or feeling"],
  ["blame", "v.", "to hold someone responsible for a fault"],
  ["boast", "v.", "to speak with excessive pride"],
  ["borrow", "v.", "to take something with the intention of returning it"],
  ["brave", "adj.", "showing courage in the face of danger"],
  ["brief", "adj.", "lasting only a short time"],
  ["brilliant", "adj.", "exceptionally clever or impressive"],
  ["calm", "adj.", "free from excitement or disturbance"],
  ["capable", "adj.", "having the ability to do something"],
  ["capture", "v.", "to take control of by force or skill"],
  ["careless", "adj.", "not giving enough attention to avoid mistakes"],
  ["cautious", "adj.", "careful to avoid danger or mistakes"],
  ["celebrate", "v.", "to mark an occasion with enjoyment"],
  ["challenge", "n.", "a task that tests someone's abilities"],
  ["cheerful", "adj.", "noticeably happy and positive"],
  ["clever", "adj.", "quick to understand and learn"],
  ["collapse", "v.", "to fall down or fail suddenly"],
  ["collect", "v.", "to bring together items from various sources"],
  ["combine", "v.", "to join or merge two or more things"],
  ["comfort", "n.", "a state of physical ease and freedom from pain"],
  ["common", "adj.", "occurring frequently; widespread"],
  ["compare", "v.", "to examine similarities and differences"],
  ["compete", "v.", "to strive to gain something against others"],
  ["complain", "v.", "to express dissatisfaction about something"],
  ["complete", "adj.", "having all necessary parts; finished"],
  ["concern", "n.", "a feeling of worry"],
  ["confident", "adj.", "feeling certain about one's abilities"],
  ["confuse", "v.", "to make someone unable to understand"],
  ["connect", "v.", "to join or link together"],
  ["consider", "v.", "to think carefully about something"],
  ["constant", "adj.", "occurring continuously over time"],
  ["contain", "v.", "to hold or include something within"],
  ["continue", "v.", "to keep happening or doing something"],
  ["contrast", "n.", "a noticeable difference between things"],
  ["convince", "v.", "to persuade someone that something is true"],
  ["cooperate", "v.", "to work jointly with others toward a goal"],
  ["courage", "n.", "the ability to face fear or danger"],
  ["create", "v.", "to bring something into existence"],
  ["crucial", "adj.", "extremely important; decisive"],
  ["curious", "adj.", "eager to learn or know something"],
  ["damage", "n.", "physical harm that reduces value or usefulness"],
  ["decide", "v.", "to reach a conclusion after consideration"],
  ["declare", "v.", "to state something clearly and officially"],
  ["decrease", "v.", "to become smaller in size or amount"],
  ["defend", "v.", "to protect from harm or criticism"],
  ["definite", "adj.", "clearly stated and not vague"],
  ["delay", "v.", "to make something happen later than planned"],
  ["delicate", "adj.", "easily damaged or requiring careful handling"],
  ["deliver", "v.", "to bring something to a destination"],
  ["demand", "v.", "to ask for something firmly"],
  ["deny", "v.", "to state that something is not true"],
  ["depend", "v.", "to rely on someone or something"],
  ["describe", "v.", "to give a detailed account in words"],
  ["desire", "n.", "a strong feeling of wanting something"],
  ["detail", "n.", "a small individual feature or fact"],
  ["determine", "v.", "to establish something firmly through investigation"],
  ["develop", "v.", "to grow or cause to grow over time"],
  ["device", "n.", "a tool made for a particular purpose"],
  ["differ", "v.", "to be unlike or disagree"],
  ["difficult", "adj.", "needing effort or skill to accomplish"],
  ["disappear", "v.", "to cease to be visible"],
  ["discover", "v.", "to find something for the first time"],
  ["discuss", "v.", "to talk about something with others"],
  ["dismiss", "v.", "to send away or refuse to consider"],
  ["distance", "n.", "the amount of space between two points"],
  ["disturb", "v.", "to interrupt or interfere with"],
];

const MEDIUM_ROWS: Row[] = [
  ["abundant", "adj.", "existing in large quantities; plentiful"],
  ["accelerate", "v.", "to increase in speed"],
  ["accessible", "adj.", "able to be reached or used easily"],
  ["accommodate", "v.", "to provide lodging or fit in with needs"],
  ["accomplish", "v.", "to achieve or complete successfully"],
  ["accumulate", "v.", "to gather together over time"],
  ["acquire", "v.", "to gain possession of something"],
  ["adapt", "v.", "to adjust to new conditions"],
  ["adequate", "adj.", "satisfactory or acceptable in quality"],
  ["adjacent", "adj.", "next to or adjoining something"],
  ["advocate", "v.", "to publicly support a cause"],
  ["aesthetic", "adj.", "concerned with beauty or artistic appeal"],
  ["aggregate", "n.", "a whole formed by combining parts"],
  ["alleviate", "v.", "to make suffering less severe"],
  ["ambiguous", "adj.", "open to more than one interpretation"],
  ["ambitious", "adj.", "having a strong desire for success"],
  ["amiable", "adj.", "friendly and pleasant in manner"],
  ["analogy", "n.", "a comparison between two similar things"],
  ["anticipate", "v.", "to expect or predict something"],
  ["apathy", "n.", "a lack of interest or concern"],
  ["arbitrary", "adj.", "based on random choice rather than reason"],
  ["articulate", "adj.", "able to express ideas clearly"],
  ["ascertain", "v.", "to find out for certain"],
  ["assert", "v.", "to state a fact or belief confidently"],
  ["authentic", "adj.", "genuine and of undisputed origin"],
  ["autonomous", "adj.", "acting independently, without outside control"],
  ["benevolent", "adj.", "kind and generous in intention"],
  ["bias", "n.", "a tendency to favor one side unfairly"],
  ["candid", "adj.", "truthful and straightforward"],
  ["coherent", "adj.", "logical and consistent"],
  ["collaborate", "v.", "to work jointly with others on a task"],
  ["complement", "v.", "to complete or enhance something"],
  ["comprehensive", "adj.", "covering all aspects thoroughly"],
  ["conceive", "v.", "to form an idea or plan in the mind"],
  ["concise", "adj.", "giving information clearly in few words"],
  ["conform", "v.", "to comply with rules or standards"],
  ["congruent", "adj.", "in agreement or harmony"],
  ["conscientious", "adj.", "careful to do things correctly and thoroughly"],
  ["consensus", "n.", "general agreement among a group"],
  ["constitute", "v.", "to be a part of a whole"],
  ["contemplate", "v.", "to think deeply about something"],
  ["contradict", "v.", "to state the opposite of something said"],
  ["conventional", "adj.", "based on what is generally done"],
  ["credible", "adj.", "able to be believed; convincing"],
  ["criteria", "n.", "standards used to judge something"],
  ["cultivate", "v.", "to develop or improve through effort"],
  ["deduce", "v.", "to reach a conclusion through reasoning"],
  ["deficient", "adj.", "lacking a necessary quality or element"],
  ["deliberate", "adj.", "done consciously and intentionally"],
  ["denote", "v.", "to be a sign or indication of"],
  ["deplete", "v.", "to reduce the amount of something"],
  ["designate", "v.", "to officially appoint or select"],
  ["deter", "v.", "to discourage someone from an action"],
  ["diligent", "adj.", "showing careful and persistent effort"],
  ["diminish", "v.", "to make or become smaller"],
  ["discern", "v.", "to perceive or recognize something clearly"],
  ["discrepancy", "n.", "a difference between things expected to match"],
  ["disseminate", "v.", "to spread information widely"],
  ["distinct", "adj.", "clearly different or separate"],
  ["diverse", "adj.", "showing a great deal of variety"],
  ["dominant", "adj.", "most powerful or influential"],
  ["dubious", "adj.", "not to be relied upon; suspect"],
  ["eclectic", "adj.", "drawing from many different sources"],
  ["elaborate", "adj.", "detailed and complicated in design"],
  ["elicit", "v.", "to draw out a response or reaction"],
  ["eloquent", "adj.", "fluent and persuasive in speech"],
  ["emulate", "v.", "to try to match by imitation"],
  ["endorse", "v.", "to publicly declare support for something"],
  ["enhance", "v.", "to improve the quality of something"],
  ["epitome", "n.", "a perfect example of a quality"],
  ["equitable", "adj.", "fair and impartial"],
  ["erode", "v.", "to gradually wear away"],
  ["evaluate", "v.", "to judge the value or quality of"],
  ["exemplify", "v.", "to be a typical example of"],
  ["exert", "v.", "to apply force or influence"],
  ["exhaustive", "adj.", "thorough and complete"],
  ["explicit", "adj.", "stated clearly and in detail"],
  ["facilitate", "v.", "to make an action easier"],
  ["feasible", "adj.", "possible to do easily or conveniently"],
  ["fluctuate", "v.", "to rise and fall irregularly"],
  ["formidable", "adj.", "inspiring fear or respect through strength"],
  ["fundamental", "adj.", "forming a necessary base or core"],
  ["hierarchy", "n.", "a system ranked by status or authority"],
  ["hypothesis", "n.", "a proposed explanation based on limited evidence"],
  ["illustrate", "v.", "to explain or clarify by using examples"],
  ["immerse", "v.", "to involve oneself deeply in an activity"],
  ["impartial", "adj.", "treating all sides equally; unbiased"],
  ["implement", "v.", "to put a plan into effect"],
  ["implicit", "adj.", "suggested though not directly stated"],
  ["imply", "v.", "to indicate without stating directly"],
  ["incentive", "n.", "something that motivates action"],
  ["inevitable", "adj.", "certain to happen; unavoidable"],
  ["infer", "v.", "to conclude from evidence and reasoning"],
  ["inherent", "adj.", "existing as a natural part of something"],
  ["innovate", "v.", "to introduce new ideas or methods"],
  ["integral", "adj.", "necessary to make something complete"],
  ["integrity", "n.", "the quality of being honest and consistent"],
  ["intricate", "adj.", "very detailed and complicated"],
  ["intuitive", "adj.", "understood instinctively without conscious reasoning"],
  ["jeopardize", "v.", "to put something at risk of harm"],
];

const HARD_ROWS: Row[] = [
  ["abstemious", "adj.", "restrained in eating or drinking"],
  ["acrimonious", "adj.", "bitter and sharp in tone"],
  ["admonish", "v.", "to warn or scold gently"],
  ["alacrity", "n.", "brisk eagerness or readiness"],
  ["anachronistic", "adj.", "belonging to a different time period"],
  ["antipathy", "n.", "a deep-seated feeling of dislike"],
  ["apocryphal", "adj.", "of doubtful authenticity, though widely circulated"],
  ["arcane", "adj.", "understood by only a few; mysterious"],
  ["ascetic", "adj.", "practicing severe self-discipline and avoiding pleasure"],
  ["assiduous", "adj.", "showing great care and perseverance"],
  ["audacious", "adj.", "showing bold, often reckless courage"],
  ["austere", "adj.", "severe or strict in manner; plain"],
  ["avarice", "n.", "extreme greed for wealth"],
  ["banal", "adj.", "lacking originality; boring"],
  ["belie", "v.", "to give a false impression of"],
  ["bellicose", "adj.", "eager to fight; aggressive"],
  ["bombastic", "adj.", "high-sounding but with little meaning"],
  ["bucolic", "adj.", "relating to pleasant rural life"],
  ["cacophony", "n.", "a harsh mixture of discordant sounds"],
  ["capitulate", "v.", "to surrender or give in"],
  ["castigate", "v.", "to criticize severely"],
  ["caustic", "adj.", "sarcastic in a hurtful, biting way"],
  ["chicanery", "n.", "the use of trickery to deceive"],
  ["circumlocution", "n.", "the use of many words to avoid being direct"],
  ["circumspect", "adj.", "wary and careful about consequences"],
  ["clandestine", "adj.", "kept secret, often for an illicit purpose"],
  ["cloying", "adj.", "excessive to the point of distaste"],
  ["coalesce", "v.", "to come together to form one whole"],
  ["cogent", "adj.", "clear, logical, and convincing"],
  ["complacent", "adj.", "uncritically satisfied with oneself"],
  ["conflagration", "n.", "a large, destructive fire"],
  ["connoisseur", "n.", "an expert judge in matters of taste"],
  ["contentious", "adj.", "likely to cause disagreement"],
  ["conundrum", "n.", "a confusing and difficult problem"],
  ["convoluted", "adj.", "extremely complex and hard to follow"],
  ["copious", "adj.", "abundant in supply or quantity"],
  ["corroborate", "v.", "to confirm or support with evidence"],
  ["debacle", "n.", "a sudden and humiliating failure"],
  ["decorous", "adj.", "showing correct, polite behavior"],
  ["deleterious", "adj.", "causing harm or damage"],
  ["demagogue", "n.", "a leader who exploits popular prejudices"],
  ["deracinate", "v.", "to remove from a native environment"],
  ["derivative", "adj.", "imitative of the work of another; unoriginal"],
  ["despot", "n.", "a ruler with absolute, often cruel power"],
  ["diaphanous", "adj.", "light and delicate enough to see through"],
  ["diatribe", "n.", "a forceful, bitter verbal attack"],
  ["dichotomy", "n.", "a division into two opposite parts"],
  ["didactic", "adj.", "intended to teach a moral lesson"],
  ["diffident", "adj.", "lacking confidence in oneself"],
  ["disingenuous", "adj.", "not candid, especially in a pretended way"],
  ["disparage", "v.", "to regard or describe as of little worth"],
  ["disparate", "adj.", "essentially different in kind"],
  ["dissemble", "v.", "to conceal one's true feelings or motives"],
  ["dogged", "adj.", "persistent and unwavering in effort"],
  ["duplicity", "n.", "deceitfulness; double-dealing"],
  ["ebullient", "adj.", "overflowing with enthusiasm"],
  ["effrontery", "n.", "shameless boldness"],
  ["egregious", "adj.", "outstandingly bad; flagrant"],
  ["elegy", "n.", "a mournful poem, especially for the dead"],
  ["elucidate", "v.", "to make something clear through explanation"],
  ["emollient", "adj.", "softening or soothing"],
  ["empirical", "adj.", "based on observation rather than theory"],
  ["enervate", "v.", "to drain of energy or vitality"],
  ["enigmatic", "adj.", "mysterious and difficult to interpret"],
  ["ephemeral", "adj.", "lasting for a very short time"],
  ["equivocal", "adj.", "deliberately open to more than one interpretation"],
  ["erudite", "adj.", "having great knowledge from study"],
  ["esoteric", "adj.", "understood by only a small, specialized group"],
  ["euphemism", "n.", "a mild expression substituted for a harsh one"],
  ["exacerbate", "v.", "to make a problem worse"],
  ["exculpate", "v.", "to clear from blame"],
  ["exigent", "adj.", "pressing; demanding immediate attention"],
  ["expedient", "adj.", "convenient and practical though possibly improper"],
  ["extol", "v.", "to praise enthusiastically"],
  ["extraneous", "adj.", "irrelevant or unnecessary"],
  ["facetious", "adj.", "joking inappropriately about serious matters"],
  ["fastidious", "adj.", "very attentive to detail; hard to please"],
  ["fatuous", "adj.", "silly and pointless"],
  ["fecund", "adj.", "highly fertile or productive"],
  ["felicitous", "adj.", "well-chosen or apt in expression"],
  ["fervent", "adj.", "showing intense and sincere passion"],
  ["flagrant", "adj.", "conspicuously bad or offensive"],
  ["florid", "adj.", "excessively elaborate or ornate"],
  ["fortuitous", "adj.", "happening by lucky chance"],
  ["fractious", "adj.", "irritable and difficult to control"],
  ["garrulous", "adj.", "excessively talkative"],
  ["gratuitous", "adj.", "uncalled for; unnecessary"],
  ["gregarious", "adj.", "fond of company; sociable"],
  ["grandiloquent", "adj.", "pompous or extravagant in language"],
  ["hackneyed", "adj.", "overused and no longer original"],
  ["hedonist", "n.", "one who pursues pleasure as life's main goal"],
  ["hegemony", "n.", "dominance of one group or state over others"],
  ["heretical", "adj.", "contrary to accepted or orthodox belief"],
  ["histrionic", "adj.", "excessively theatrical or dramatic"],
  ["iconoclast", "n.", "one who attacks cherished beliefs or institutions"],
  ["idiosyncratic", "adj.", "peculiar to an individual"],
  ["ignominious", "adj.", "deserving or causing public disgrace"],
  ["imperious", "adj.", "arrogantly domineering"],
  ["impervious", "adj.", "unable to be affected or penetrated"],
  ["implacable", "adj.", "unable to be appeased or calmed"],
];

export const VOCAB_WORDS: Record<VocabDifficulty, VocabWord[]> = {
  easy: toWords(EASY_ROWS),
  medium: toWords(MEDIUM_ROWS),
  hard: toWords(HARD_ROWS),
};

export const VOCAB_DIFFICULTIES: VocabDifficulty[] = ["easy", "medium", "hard"];
