ALTER TABLE public.lesson_progress
  ADD COLUMN IF NOT EXISTS current_step INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS pass_count INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS avg_wpm NUMERIC DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS avg_accuracy NUMERIC DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS total_time_ms BIGINT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ;
ALTER TABLE public.lesson_progress
  ADD COLUMN IF NOT EXISTS typed_chars INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS correct_chars INTEGER DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS incorrect_chars INTEGER DEFAULT 0 NOT NULL;
